### PR TITLE
feat: add hook data support

### LINKED ISSUE #151: Hook review support
We need to handle hook reviews in the same way we handle rate provider reviews on pool pages.

- Render the information
- Block actions and display warnings under certain conditions.

Designs: https://www.figma.com/design/97sJd9iKmVWDsPIUdHGxTk/v3-App-Pools-Launch?node-id=0-1&t=FqwfjgPU5WOdvOwr-1

### PR DESCRIPTION
**Pull request by groninge01**
fixes #151

### CODE REVIEW

**Comment by groninge01** [comment]
https://balancer.fi/risks#hook-risk will need copy

**Comment by groninge01** [comment]
api changed -> converted to draft

**Comment by groninge01** [comment]
synced with api again

**Comment by garethfuller** [comment]
@alter-eggo can you check if this unit test failure is because of this PR please?

**Pull request merged**
